[package]
name = "try-serde"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_derive = "1.0.188"
serde = "1.0.188"
serde_json = "1.0.107"
serde_yaml = "0.9.25"